"use client";

import { useEffect, useState, use } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { motion } from "framer-motion";
import {
    generateEmail,
    regenerateEmail,
    getMatchDetail,
    type EmailResponse,
    type MentorSnapshot,
} from "@/lib/api";
import EmailPreview from "@/components/EmailPreview";

interface PageProps {
    params: Promise<{ sessionId: string; mentorId: string }>;
}

export default function EmailPage({ params }: PageProps) {
    const { sessionId, mentorId } = use(params);
    const router = useRouter();
    const searchParams = useSearchParams();
    const score = parseFloat(searchParams.get("score") || "0.5");

    const [emailData, setEmailData] = useState<EmailResponse | null>(null);
    const [mentor, setMentor] = useState<MentorSnapshot | null>(null);
    const [loading, setLoading] = useState(true);
    const [regenerating, setRegenerating] = useState(false);
    const [error, setError] = useState("");

    useEffect(() => {
        async function load() {
            try {
                const [emailRes, mentorRes] = await Promise.all([
                    generateEmail({
                        student_id: sessionId,
                        mentor_id: mentorId,
                        match_score: score,
                    }),
                    getMatchDetail(mentorId),
                ]);
                setEmailData(emailRes);
                setMentor(mentorRes.snapshot);
            } catch (err: unknown) {
                setError(err instanceof Error ? err.message : "Failed to generate email.");
            } finally {
                setLoading(false);
            }
        }
        load();
    }, [sessionId, mentorId, score]);

    const handleRegenerate = async () => {
        setRegenerating(true);
        try {
            const res = await regenerateEmail({
                student_id: sessionId,
                mentor_id: mentorId,
                match_score: score,
            });
            setEmailData(res);
        } catch (err: unknown) {
            setError(err instanceof Error ? err.message : "Regeneration failed.");
        } finally {
            setRegenerating(false);
        }
    };

    if (loading) {
        return (
            <div className="min-h-[calc(100vh-4rem)] flex items-center justify-center">
                <div className="flex flex-col items-center gap-4">
                    <span className="inline-block w-10 h-10 border-3 border-[var(--color-primary)]/30 border-t-[var(--color-primary)] rounded-full animate-spin" />
                    <p className="text-[var(--color-muted)]">Crafting your icebreaker email...</p>
                </div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="min-h-[calc(100vh-4rem)] flex items-center justify-center px-4">
                <div className="glass rounded-2xl p-8 text-center max-w-md">
                    <p className="text-xl mb-2">😕</p>
                    <p className="text-[var(--color-danger)] mb-4">{error}</p>
                    <button onClick={() => router.back()} className="btn-primary">
                        ← Go Back
                    </button>
                </div>
            </div>
        );
    }

    return (
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-10 space-y-8">
            {/* Header */}
            <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
                <button
                    onClick={() => router.back()}
                    className="text-sm text-[var(--color-muted)] hover:text-[var(--color-foreground)] transition-colors mb-4"
                >
                    ← Back to Results
                </button>
                <h1 className="text-3xl font-bold">
                    Connect with{" "}
                    <span className="gradient-text">{emailData?.mentor_label || "Mentor"}</span>
                </h1>
                {emailData?.provider && (
                    <p className="text-xs mt-2 text-[var(--color-muted)]">
                        Generated by <span className="font-semibold uppercase">{emailData.provider}</span>
                        {emailData.model ? ` · ${emailData.model}` : ""}
                        {emailData.used_fallback ? " · fallback used" : ""}
                    </p>
                )}
            </motion.div>

            {/* Mentor snapshot */}
            {mentor && (
                <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.1 }}
                    className="glass rounded-2xl p-6"
                >
                    <h2 className="font-semibold mb-3 text-sm uppercase tracking-wider text-[var(--color-muted)]">
                        Mentor Profile
                    </h2>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-sm">
                        <div>
                            <p className="text-[var(--color-muted)] text-xs mb-1">Title</p>
                            <p className="font-medium">{mentor.current_title || "N/A"}</p>
                        </div>
                        <div>
                            <p className="text-[var(--color-muted)] text-xs mb-1">Level</p>
                            <p className="font-medium">{mentor.current_level || "N/A"}</p>
                        </div>
                        <div>
                            <p className="text-[var(--color-muted)] text-xs mb-1">Industry</p>
                            <p className="font-medium">{mentor.industry || "N/A"}</p>
                        </div>
                        <div>
                            <p className="text-[var(--color-muted)] text-xs mb-1">Match Score</p>
                            <p className="font-medium text-[var(--color-primary)]">
                                {Math.round(score * 100)}%
                            </p>
                        </div>
                    </div>
                    {mentor.education_summary.length > 0 && (
                        <div className="mt-4">
                            <p className="text-[var(--color-muted)] text-xs mb-1.5">Education</p>
                            <div className="flex flex-wrap gap-2">
                                {mentor.education_summary.map((edu, i) => (
                                    <span
                                        key={i}
                                        className="text-xs px-2.5 py-1 rounded-full bg-[var(--color-surface)] border border-[var(--color-border)]"
                                    >
                                        {edu.degree || "Degree"}{edu.field ? ` in ${edu.field}` : ""}
                                    </span>
                                ))}
                            </div>
                        </div>
                    )}
                </motion.div>
            )}

            {/* Email preview */}
            {emailData && (
                <EmailPreview
                    email={emailData.email}
                    mentorLabel={emailData.mentor_label}
                    matchScore={emailData.match_score}
                    onRegenerate={handleRegenerate}
                    isRegenerating={regenerating}
                />
            )}

            {/* Tips */}
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.3 }}
                className="glass rounded-2xl p-6"
            >
                <h3 className="font-semibold mb-3">💡 Tips for Reaching Out</h3>
                <ul className="space-y-2 text-sm text-[var(--color-muted)]">
                    <li>✅ Send the email through LinkedIn InMail or their public contact</li>
                    <li>✅ Mention a specific part of their career that inspires you</li>
                    <li>✅ Keep your ask simple — a 15-minute call is ideal</li>
                    <li>✅ Follow up once if you don&apos;t hear back within a week</li>
                    <li>⚠️ Never share sensitive personal details in your first message</li>
                </ul>
            </motion.div>
        </div>
    );
}
